[env:genericCH32V317WCU6]
platform = ch32v
board = genericCH32V317WCU6
framework = 

board_build.ldscript = Link.ld
board_build.march = rv32imafcxw
board_build.mabi = ilp32f

build_flags = 
    -mcmodel=medlow
    -mno-save-restore
    -O2
    -DU_HOST_FS
    -mno-relax
    -DCH32V30x_D8C
    -Iinclude
    -Ilib/ch32v30x/inc
    -Ilib/FreeRTOS/include
    -Ilib/FreeRTOS/portable/GCC/RISC-V
    -Isrc/USB_Host

upload_protocol = wch-link
debug_tool = wch-link

; Очищаем триггеры, делаем жесткий останов ядра на физическом сбросе
debug_init_break = 
debug_extra_cmds =
    monitor reset halt
